"""empty message

Revision ID: 1d89fc8aa264
Revises: be744126c407
Create Date: 2021-04-08 10:55:57.742259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d89fc8aa264'
down_revision = 'be744126c407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('state', sa.String(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE PLANTS SET STATE='TOGO';")

    op.alter_column('plants','state',nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'state')
    # ### end Alembic commands ###

